name: CreeperHeal
main: com.nitnelave.CreeperHeal.CreeperHeal
version: 2.2
author: nitnelave
description: Replaces terrain destroyed by creeper explosions

commands:
    CreeperHeal:
        description: CreeperHeal commands
        usage: /<command> [heal|Creeper|TNT|dropReplaced|fire|burnInterval|ghast|magical]
        permissions: CreeperHeal.admin
        aliases: ch
