name: CreeperHeal
main: com.nitnelave.CreeperHeal.CreeperHeal
version: 3.0
author: nitnelave
description: Replaces terrain destroyed by creeper explosions

commands:
    CreeperHeal:
        description: CreeperHeal commands
        usage: /<command> [trap|heal|Creeper|TNT|interval|dropReplaced|fire|burnInterval|ghast|magical|healBurnt]
        permissions: CreeperHeal.admin
        aliases: ch
