name: CreeperHeal
main: com.nitnelave.CreeperHeal.CreeperHeal
version: 1.3
author: nitnelave
description: Replaces terrain destroyed by creeper explosions

commands:
    CreeperHeal:
        description: CreeperHeal commands
        usage: /<command> [forceHeal|Creeper|TNT|dropReplaced|fire|burnInterval]
        permissions: CreeperHeal.admin
        aliases: ch
