name: CreeperHeal
main: com.nitnelave.CreeperHeal.CreeperHeal
version: 3.2.4
author: nitnelave
description: Replaces terrain destroyed by creeper explosions

commands:
    CreeperHeal:
        description: CreeperHeal commands
        usage: /<command> help
        aliases: ch
