name: GiftSend
main: com.GiftSend.GiftSend.GiftSend
version: 0.5.1
author: nitnelave
commands:
    send:
        description: Send items to other players. Defaults to item in hand.
        usage: /<command> [playername] [amount] (item_id or name) (damage/durability)
        aliases: gift
